=== raml-apis/Zuora/schemas/accounts-schema.json
{
            "required" : true ,
            "$schema" : "http://json-schema.org/draft-03/schema" ,
            "type" : "object" ,
            "properties" : {
              "creditCard" : {
                "type" : "object" ,
                "required" : false
              } ,
              "invoiceTargetDate" : {
                "type" : "string" ,
                "required" : false
              } ,
              "name" : {
                "type" : "string" ,
                "required" : true
              } ,
              "billCycleDay" : {
                "type" : "string" ,
                "required" : false
              } ,
              "soldToContact" : {
                "type" : "object" ,
                "required" : false
              } ,
              "billToContact" : {
                "type" : "object" ,
                "required" : true ,
                "properties" : {
                  "country" : {
                    "type" : "string" ,
                    "required" : false
                  } ,
                  "lastName" : {
                    "type" : "string" ,
                    "required" : true
                  } ,
                  "workEmail" : {
                    "type" : "string" ,
                    "required" : false
                  } ,
                  "address1" : {
                    "type" : "string" ,
                    "required" : false
                  } ,
                  "address2" : {
                    "type" : "string" ,
                    "required" : false
                  } ,
                  "state" : {
                    "type" : "string" ,
                    "required" : false
                  } ,
                  "firstName" : {
                    "type" : "string" ,
                    "required" : true
                  } ,
                  "city" : {
                    "type" : "string" ,
                    "required" : false
                  } ,
                  "mobilePhone" : {
                    "type" : "string" ,
                    "required" : false
                  }
                }
              } ,
              "invoiceCollect" : {
                "type" : "boolean" ,
                "required" : false
              } ,
              "notes" : {
                "type" : "string" ,
                "required" : false
              } ,
              "subscription" : {
                "type" : "object" ,
                "required" : false ,
                "properties" : {
                  "subscribeToRatePlans" : {
                    "type" : "array" ,
                    "required" : false ,
                    "items" : 
                      {
                        "type" : "object" ,
                        "properties" : {
                          "productRatePlanId" : {
                            "type" : "string" ,
                            "required" : true
                          } ,
                          "chargeOverrides" : {
                            "type" : "array" ,
                            "required" : false ,
                            "items" : 
                              {
                                "type" : "object" ,
                                "properties" : {
                                  "productRatePlanChargeId" : {
                                    "type" : "string" ,
                                    "required" : true
                                  } ,
                                  "quantity" : {
                                    "type" : "number" ,
                                    "required" : true
                                  }
                                }
                              }
                            
                          }
                        }
                      }
                    
                  } ,
                  "contractEffectiveDate" : {
                    "type" : "string" ,
                    "required" : true
                  } ,
                  "initialTerm" : {
                    "type" : "string" ,
                    "required" : false
                  } ,
                  "autoRenew" : {
                    "type" : "boolean" ,
                    "required" : false
                  } ,
                  "termType" : {
                    "type" : "string" ,
                    "required" : true
                  } ,
                  "renewalTerm" : {
                    "type" : "string" ,
                    "required" : false
                  } ,
                  "myCustomField__c" : {
                    "type" : "string" ,
                    "required" : false
                  }
                }
              } ,
              "paymentTerm" : {
                "type" : "string" ,
                "required" : false
              } ,
              "currency" : {
                "type" : "string" ,
                "required" : true
              } ,
              "myCustomField__c" : {
                "type" : "string" ,
                "required" : false
              }
            }
          }

=== raml-apis/Zuora/examples/accounts-example.json
{
  "creditCard" : {
    "cardType" : "Visa" ,
    "expirationMonth" : 2 ,
    "securityCode" : "111" ,
    "cardNumber" : "4856200223544175" ,
    "expirationYear" : 2014
  } ,
  "invoiceTargetDate" : "2013-12-31" ,
  "name" : "Soho" ,
  "billCycleDay" : "15" ,
  "soldToContact" : {
    "country" : "USA" ,
    "lastName" : "Doe" ,
    "workEmail" : "john.doe@zoura.com" ,
    "address1" : "address1" ,
    "address2" : "address2" ,
    "firstName" : "John" ,
    "state" : "California" ,
    "city" : "San Francisco" ,
    "mobilePhone" : "14156789012"
  } ,
  "billToContact" : {
    "country" : "USA" ,
    "lastName" : "Doe" ,
    "workEmail" : "jane.doe@zoura.com" ,
    "address1" : "address1" ,
    "address2" : "address2" ,
    "state" : "California" ,
    "firstName" : "Jane" ,
    "city" : "San Francisco" ,
    "mobilePhone" : "14156789012"
  } ,
  "invoiceCollect" : true ,
  "notes" : "Soho Networks" ,
  "subscription" : {
    "subscribeToRatePlans" : [
      {
        "productRatePlanId" : "4028e48735bd88440135c007d07e3169" ,
        "chargeOverrides" : [
          {
            "productRatePlanChargeId" : "4028e48835a944f50135c00862171ab3" ,
            "quantity" : 10
          }
        ]
      }
    ] ,
    "contractEffectiveDate" : "2013-02-1" ,
    "initialTerm" : "12" ,
    "autoRenew" : true ,
    "termType" : "TERMED" ,
    "renewalTerm" : "3" ,
    "myCustomField__c" : "test"
  } ,
  "paymentTerm" : "Net 30" ,
  "currency" : "USD" ,
  "myCustomField__c" : "Sally"
}
