=== raml-apis/Zuora/schemas/accountCreated-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "paymentMethodId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "paymentId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "paidAmount" : {
      "type" : "number" ,
      "required" : false
    } ,
    "subscriptionNumber" : {
      "type" : "string" ,
      "required" : false
    } ,
    "subscriptionId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accountId" : {
      "type" : "string" ,
      "required" : false
    } ,
    "success" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "accountNumber" : {
      "type" : "string" ,
      "required" : false
    } ,
    "invoiceId" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Zuora/examples/accountCreated-example.json
{
  "paymentMethodId" : "2c92c8f83dcbd8b1013dcce096b0000b" ,
  "paymentId" : "2c92c8f83dcbd8b1013dcce09f420032" ,
  "paidAmount" : 599.55 ,
  "subscriptionNumber" : "A-S00001083" ,
  "subscriptionId" : "2c92c8f83dcbd8b1013dcce0983b0015" ,
  "accountId" : "2c92c8f83dcbd8b1013dcce096790008" ,
  "success" : true ,
  "accountNumber" : "A00030968" ,
  "invoiceId" : "2c92c8f83dcbd8b1013dcce09d110025"
}
