=== raml-apis/Zuora/schemas/paymentMethodPostBody-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "defaultPaymentMethod" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "cardHolderInfo" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "addressLine1" : {
          "type" : "string" ,
          "required" : false
        } ,
        "addressLine2" : {
          "type" : "string" ,
          "required" : false
        } ,
        "zipCode" : {
          "type" : "string" ,
          "required" : false
        } ,
        "state" : {
          "type" : "string" ,
          "required" : false
        } ,
        "phone" : {
          "type" : "string" ,
          "required" : false
        } ,
        "country" : {
          "type" : "string" ,
          "required" : false
        } ,
        "cardHolderName" : {
          "type" : "string" ,
          "required" : false
        } ,
        "city" : {
          "type" : "string" ,
          "required" : false
        } ,
        "email" : {
          "type" : "string" ,
          "required" : false
        }
      }
    } ,
    "expirationMonth" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accountKey" : {
      "type" : "string" ,
      "required" : false
    } ,
    "creditCardType" : {
      "type" : "string" ,
      "required" : false
    } ,
    "expirationYear" : {
      "type" : "string" ,
      "required" : false
    } ,
    "creditCardNumber" : {
      "type" : "string" ,
      "required" : false
    } ,
    "securityCode" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Zuora/examples/paymentMethodPostBody-example.json
{
  "defaultPaymentMethod" : false ,
  "cardHolderInfo" : {
    "addressLine1" : "77 Fallon Glen" ,
    "addressLine2" : "" ,
    "zipCode" : "94020" ,
    "state" : "California" ,
    "phone" : "4155551234" ,
    "country" : "USA" ,
    "cardHolderName" : "Bill Thiebault" ,
    "city" : "Fremont" ,
    "email" : "bill@testaddress.com"
  } ,
  "expirationMonth" : "10" ,
  "accountKey" : "A00001115" ,
  "creditCardType" : "Discover" ,
  "expirationYear" : "2015" ,
  "creditCardNumber" : "1111222233334444" ,
  "securityCode" : "123"
}
