=== raml-apis/Zuora/schemas/subscriptionPutBody-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "renewalTerm" : {
      "type" : "string" ,
      "required" : false
    } ,
    "termType" : {
      "type" : "string" ,
      "required" : false
    } ,
    "autoRenew" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "currentTerm" : {
      "type" : "string" ,
      "required" : false
    } ,
    "update" : {
      "type" : "array" ,
      "required" : false ,
      "items" : 
        {
          "type" : "object" ,
          "properties" : {
            "ratePlanId" : {
              "type" : "string" ,
              "required" : false
            } ,
            "contractEffectiveDate" : {
              "type" : "string" ,
              "required" : false
            } ,
            "chargeUpdateDetails" : {
              "type" : "array" ,
              "required" : false ,
              "items" : 
                {
                  "type" : "object" ,
                  "properties" : {
                    "ratePlanChargeId" : {
                      "type" : "string" ,
                      "required" : false
                    } ,
                    "quantity" : {
                      "type" : "number" ,
                      "required" : false
                    }
                  }
                }
              
            }
          }
        }
      
    } ,
    "notes" : {
      "type" : "string" ,
      "required" : false
    } ,
    "myCustomField__c" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Zuora/examples/subscriptionPutBody-example.json
{
  "renewalTerm" : "4" ,
  "termType" : "TERMED" ,
  "autoRenew" : false ,
  "currentTerm" : "10" ,
  "update" : [
    {
      "ratePlanId" : "2c92c8f83dcbd8b1013dcce0ea7e006f" ,
      "contractEffectiveDate" : "2013-04-28" ,
      "chargeUpdateDetails" : [
        {
          "ratePlanChargeId" : "2c92c8f83dcbd8b1013dcce0eb510075" ,
          "quantity" : 12
        }
      ]
    }
  ] ,
  "notes" : "Test UPDATE subscription from z-ruby-sdk" ,
  "myCustomField__c" : "test"
}
