=== raml-apis/Zuora/schemas/subscriptionsPreviewBody-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "termType" : {
      "type" : "string" ,
      "required" : true
    } ,
    "invoiceTargetDate" : {
      "type" : "string" ,
      "required" : false
    } ,
    "contractEffectiveDate" : {
      "type" : "string" ,
      "required" : true
    } ,
    "previewAccountInfo" : {
      "type" : "object" ,
      "required" : false ,
      "properties" : {
        "currency" : {
          "type" : "string" ,
          "required" : false
        } ,
        "billToContact" : {
          "type" : "object" ,
          "required" : false ,
          "properties" : {
            "zipCode" : {
              "type" : "string" ,
              "required" : false
            } ,
            "country" : {
              "type" : "string" ,
              "required" : false
            } ,
            "city" : {
              "type" : "string" ,
              "required" : false
            } ,
            "county" : {
              "type" : "string" ,
              "required" : false
            } ,
            "state" : {
              "type" : "string" ,
              "required" : false
            }
          }
        } ,
        "billCycleDay" : {
          "type" : "number" ,
          "required" : false
        }
      }
    } ,
    "subscribeToRatePlans" : {
      "type" : "array" ,
      "required" : true ,
      "items" : 
        {
          "type" : "object" ,
          "properties" : {
            "chargeOverrides" : {
              "type" : "array" ,
              "required" : false ,
              "items" : 
                {
                  "type" : "object" ,
                  "properties" : {
                    "productRatePlanChargeId" : {
                      "type" : "string" ,
                      "required" : true
                    } ,
                    "quantity" : {
                      "type" : "number" ,
                      "required" : true
                    }
                  }
                }
              
            } ,
            "productRatePlanId" : {
              "type" : "string" ,
              "required" : true
            }
          }
        }
      
    } ,
    "initialTerm" : {
      "type" : "number" ,
      "required" : false
    }
  }
}

=== raml-apis/Zuora/examples/subscriptionsPreviewBody-example.json
{
  "termType" : "TERMED" ,
  "invoiceTargetDate" : "2013-12-31" ,
  "contractEffectiveDate" : "2013-1-15" ,
  "previewAccountInfo" : {
    "currency" : "USD" ,
    "billToContact" : {
      "zipCode" : "94549" ,
      "country" : "United States" ,
      "city" : "Walnut Creek" ,
      "county" : "Contra Consta" ,
      "state" : "California"
    } ,
    "billCycleDay" : 31
  } ,
  "subscribeToRatePlans" : [
    {
      "chargeOverrides" : [
        {
          "productRatePlanChargeId" : "ff8080811ca15d19011cddad8c953b53" ,
          "quantity" : 100
        }
      ] ,
      "productRatePlanId" : "ff8080811ca15d19011cdda9b0ad3b51"
    }
  ] ,
  "initialTerm" : 12
}
