=== raml-apis/Zuora/schemas/subscriptionPostBody-schema.json
{
  "required" : true ,
  "$schema" : "http://json-schema.org/draft-03/schema" ,
  "type" : "object" ,
  "properties" : {
    "renewalTerm" : {
      "type" : "string" ,
      "required" : false
    } ,
    "termType" : {
      "type" : "string" ,
      "required" : true
    } ,
    "autoRenew" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "invoiceTargetDate" : {
      "type" : "string" ,
      "required" : false
    } ,
    "accountKey" : {
      "type" : "string" ,
      "required" : true
    } ,
    "contractEffectiveDate" : {
      "type" : "string" ,
      "required" : true
    } ,
    "subscribeToRatePlans" : {
      "type" : "array" ,
      "required" : true ,
      "items" : 
        {
          "type" : "object" ,
          "properties" : {
            "chargeOverrides" : {
              "type" : "array" ,
              "required" : false ,
              "items" : 
                {
                  "type" : "object" ,
                  "properties" : {
                    "productRatePlanChargeId" : {
                      "type" : "string" ,
                      "required" : true
                    } ,
                    "quantity" : {
                      "type" : "number" ,
                      "required" : true
                    }
                  }
                }
              
            } ,
            "productRatePlanId" : {
              "type" : "string" ,
              "required" : true
            }
          }
        }
      
    } ,
    "invoiceCollect" : {
      "type" : "boolean" ,
      "required" : false
    } ,
    "initialTerm" : {
      "type" : "string" ,
      "required" : false
    } ,
    "notes" : {
      "type" : "string" ,
      "required" : false
    } ,
    "myCustomField__c" : {
      "type" : "string" ,
      "required" : false
    }
  }
}

=== raml-apis/Zuora/examples/subscriptionPostBody-example.json
{
  "renewalTerm" : "3" ,
  "termType" : "TERMED" ,
  "autoRenew" : true ,
  "invoiceTargetDate" : "2013-12-31" ,
  "accountKey" : "A00001115" ,
  "contractEffectiveDate" : "2013-02-1" ,
  "subscribeToRatePlans" : [
    {
      "chargeOverrides" : [
        {
          "productRatePlanChargeId" : "ff8080811ca15d19011cddad8c953b53" ,
          "quantity" : 10
        }
      ] ,
      "productRatePlanId" : "ff8080811ca15d19011cdda9b0ad3b51"
    }
  ] ,
  "invoiceCollect" : false ,
  "initialTerm" : "12" ,
  "notes" : "Test POST subscription from z-ruby-sdk" ,
  "myCustomField__c" : "test"
}
